import pandas as pd
import matplotlib.pyplot as plt

def main():
    data = pd.read_csv("sine_cosine.csv")

    n = data["n"]
    cos_vals = data["cos"]
    sin_vals = data["sin"]

    plt.figure()
    plt.plot(n, cos_vals, label="cos(nω)")
    plt.plot(n, sin_vals, label="sin(nω)")
    plt.xlabel("Sample index n")
    plt.ylabel("Amplitude")
    plt.title("Sine and cosine generated by recursive multiplication")
    plt.legend()
    plt.grid(True)
    plt.show()

if __name__ == "__main__":
    main()
